(definstances Estils
([Expressionisme] of Estil (Nom "Expressionisme"))
([Romanticisme] of Estil (Nom "Romanticisme"))
([Renaixement] of Estil (Nom "Renaixement"))
([Barroc] of Estil (Nom "Barroc"))
([Flamenc] of Estil (Nom "Escola flamenca"))
([Cubisme] of Estil (Nom "Cubisme"))
([Surrealisme] of Estil (Nom "Surrealisme"))
([Impressionisme] of Estil (Nom "Impressionisme"))
([Postimpressionisme] of Estil (Nom "Postimpressionisme"))
([NeoPlasticisme] of Estil (Nom "NeoPlasticisme"))
([Manierisme] of Estil (Nom "Manierisme"))
([Simbolisme] of Estil (Nom "Simbolisme"))
([Academicisme] of Estil (Nom "Academicisme"))
([EscolaFlorentina] of Estil (Nom "Escola Florentina"))
([Fauvisme] of Estil (Nom "Fauvisme"))
([Realisme] of Estil (Nom "Realisme"))
([Gotic] of Estil (Nom "Gòtic"))
([Romanic] of Estil (Nom "Romànic"))
([Classicisme] of Estil (Nom "Classicisme"))
([EstilAbstracte] of Estil (Nom "Abstracte"))
([Rococo] of Estil (Nom "Rococó"))
([Neoclassic] of Estil (Nom "Neoclàssic"))
([Naif] of Estil (Nom "Naïf"))
)

(definstances Tematiques
([Terror] of Tematica (Nom "Terror"))
([Guerra] of Tematica (Nom "Guerra"))
([Religio] of Tematica (Nom "Religió"))
([Retrat] of Tematica (Nom "Retrat"))
([Musica] of Tematica (Nom "Música"))
([Paisatge] of Tematica (Nom "Paisatge"))
([Abstracte] of Tematica (Nom "Abstracte"))
([Temps] of Tematica (Nom "Temps"))
([Mitologia] of Tematica (Nom "Mitologia"))
([Amor] of Tematica (Nom "Amor"))
([Mort] of Tematica (Nom "Mort"))
([Natura] of Tematica (Nom "Natura"))
([NaturaMorta] of Tematica (Nom "Natura morta"))
([Floral] of Tematica (Nom "Floral"))
([VidaQuotidiana] of Tematica (Nom "Vida quotidiana"))
([Erotisme] of Tematica (Nom "Erotisme"))
([Moral] of Tematica (Nom "Moral"))
([Pobresa] of Tematica (Nom "Pobresa"))
([Societat] of Tematica (Nom "Societat"))
([Espectacle] of Tematica (Nom "Espectacle"))
([Historia] of Tematica (Nom "Història"))
([Animals] of Tematica (Nom "Animals"))
)

(definstances Epoques
([EdatMitjana] of Època (Nom "Edat Mitjana") (Any_inici 476) (Any_final 1350))
([RenaixementEpoca] of Època (Nom "Renaixement") (Any_inici 1350) (Any_final 1620))
([Barroca] of Època (Nom "Barroca") (Any_inici 1600) (Any_final 1750))
([Neoclassica] of Època (Nom "Neoclàssica") (Any_inici 1750) (Any_final 1830))
([Romantica] of Època (Nom "Romàntica") (Any_inici 1800) (Any_final 1900))
([Moderna] of Època (Nom "Moderna") (Any_inici 1850) (Any_final 1950))
([Contemporanea] of Època (Nom "Contemporànea") (Any_inici 1920) (Any_final 2024))
)

(definstances Pintors
([Munch] of Pintor (TéEstils [Simbolisme] [Expressionisme]) (Nom "Edvard Munch") (Nacionalitat "Noruega") (TéÉpoca [Moderna]))
([Delacroix] of Pintor (TéEstils [Romanticisme]) (Nom "Ferdinand-Victor-Eugène Delacroix") (Nacionalitat "França") (TéÉpoca [Romantica]))
([Cabanel] of Pintor (TéEstils [Academicisme]) (Nom "Alexandre Cabanel") (Nacionalitat "França") (TéÉpoca [Romantica]))
([DaVinci] of Pintor (TéEstils [Renaixement]) (Nom "Leonardo da Vinci") (Nacionalitat "Itàlia") (TéÉpoca [RenaixementEpoca]))
([Velazquez] of Pintor (TéEstils [Barroc]) (Nom "Diego Rodríguez de Silva y Velázquez") (Nacionalitat "Espanya") (TéÉpoca [Barroca]))
([ElBosco] of Pintor (TéEstils [Renaixement]) (Nom "El Bosco") (Nacionalitat "Països Baixos") (TéÉpoca [RenaixementEpoca]))
([Picasso] of Pintor (TéEstils [Cubisme] [Expressionisme]) (Nom "Pablo Ruiz Picasso") (Nacionalitat "Espanya") (TéÉpoca [Contemporanea]))
([Monet] of Pintor (TéEstils [Impressionisme]) (Nom "Claude Monet") (Nacionalitat "França") (TéÉpoca [Moderna]))
([VanGogh] of Pintor (TéEstils [Postimpressionisme]) (Nom "Vincent Willem van Gogh") (Nacionalitat "Països Baixos") (TéÉpoca [Moderna]))
([Mondrian] of Pintor (TéEstils [NeoPlasticisme]) (Nom "Piet Mondrian") (Nacionalitat "Països Baixos") (TéÉpoca [Moderna]))
([Dali] of Pintor (TéEstils [Surrealisme] [Cubisme] [Simbolisme]) (Nom "Salvador Dalí") (Nacionalitat "Espanya") (TéÉpoca [Contemporanea]))
([ElGreco] of Pintor (TéEstils [Manierisme] [Renaixement]) (Nom "El Greco") (Nacionalitat "Grècia") (TéÉpoca [RenaixementEpoca]))
([MiguelAngel] of Pintor (TéEstils [Renaixement]) (Nom "Miguel Ángel") (Nacionalitat "Itàlia") (TéÉpoca [RenaixementEpoca]))
([Botticelli] of Pintor (TéEstils [Renaixement] [EscolaFlorentina]) (Nom "Sandro Botticelli") (Nacionalitat "Itàlia") (TéÉpoca [RenaixementEpoca]))
([Friedrich] of Pintor (TéEstils [Romanticisme]) (Nom "Caspar David Friedrich") (Nacionalitat "Alemanya") (TéÉpoca [Romantica]))
([Klimt] of Pintor (TéEstils [Simbolisme]) (Nom "Gustav Klimt") (Nacionalitat "Àustria") (TéÉpoca [Moderna]))
([Rembrandt] of Pintor (TéEstils [Barroc]) (Nom "Rembrandt Harmenszoon van Rijn") (Nacionalitat "Països Baixos") (TéÉpoca [Barroca]))
([Kandinsky] of Pintor (TéEstils [Expressionisme] [EstilAbstracte]) (Nom "Wassily Kandinsky") (Nacionalitat "Rússia") (TéÉpoca [Contemporanea]))
([Turner] of Pintor (TéEstils [Romanticisme]) (Nom "Joseph Mallord William Turner") (Nacionalitat "Regne Unit") (TéÉpoca [Romantica]))
([Goya] of Pintor (TéEstils [Romanticisme] [Rococo] [Neoclassic]) (Nom "Francisco de Goya") (Nacionalitat "Espanya") (TéÉpoca [Neoclassica]))
([Seurat] of Pintor (TéEstils [Puntillisme] [Impressionisme] [Postimpressionisme]) (Nom "Georges Seurat") (Nacionalitat "França") (TéÉpoca [Moderna]))
([Manet] of Pintor (TéEstils [Impressionisme]) (Nom "Édouard Manet") (Nacionalitat "França") (TéÉpoca [Moderna]))
([Cezanne] of Pintor (TéEstils [Postimpressionisme] [Cubisme]) (Nom "Paul Cézanne") (Nacionalitat "França") (TéÉpoca [Moderna]))
([Magritte] of Pintor (TéEstils [Surrealisme]) (Nom "René Magritte") (Nacionalitat "Bèlgica") (TéÉpoca [Contemporanea]))
([Hopper] of Pintor (TéEstils [Realisme]) (Nom "Edward Hopper") (Nacionalitat "Estats Units") (TéÉpoca [Contemporanea]))
([Cimabue] of Pintor (TéEstils [Gotic]) (Nom "Cimabue") (Nacionalitat "Itàlia") (TéÉpoca [EdatMitjana]))
([Giotto] of Pintor (TéEstils [Gotic]) (Nom "Giotto di Bondone") (Nacionalitat "Itàlia") (TéÉpoca [EdatMitjana]))
([Duccio] of Pintor (TéEstils [Gotic]) (Nom "Duccio di Buoninsegna") (Nacionalitat "Itàlia") (TéÉpoca [EdatMitjana]))
([MestreTahull] of Pintor (TéEstils [Romanic]) (Nom "Mestre de Tahull") (Nacionalitat "Espanya") (TéÉpoca [EdatMitjana]))
([Vermeer] of Pintor (TéEstils [Barroc]) (Nom "Johannes Verneer") (Nacionalitat "Països Baixos") (TéÉpoca [Barroca]))
([Sorolla] of Pintor (TéEstils [Postimpressionisme]) (Nom "Joaquín Sorolla") (Nacionalitat "Espanya") (TéÉpoca [Moderna]))
([Rafael] of Pintor (TéEstils [Renaixement]) (Nom "Rafaello Sanzio") (Nacionalitat "Itàlia") (TéÉpoca [RenaixementEpoca]))
([Lorrain] of Pintor (TéEstils [Classicisme]) (Nom "Claude Lorrain") (Nacionalitat "França") (TéÉpoca [Barroca]))
([Miro] of Pintor (TéEstils [Surrealisme]) (Nom "Joan Miró") (Nacionalitat "Espanya") (TéÉpoca [Contemporanea]))
([Durero] of Pintor (TéEstils [Renaixement]) (Nom "Albrecht Dürer") (Nacionalitat "Alemanya") (TéÉpoca [RenaixementEpoca]))
([Murillo] of Pintor (TéEstils [Barroc]) (Nom "Bartolomé Esteban Murillo") (Nacionalitat "Espanya") (TéÉpoca [Barroca]))
([Canaletto] of Pintor (TéEstils [Rococo]) (Nom "Canaletto") (Nacionalitat "Itàlia") (TéÉpoca [Barroca]))
([Bruegel] of Pintor (TéEstils [Renaixement] [Flamenc]) (Nom "Pieter Brueghel") (Nacionalitat "Bèlgica") (TéÉpoca [RenaixementEpoca]))
([Bronzino] of Pintor (TéEstils [Manierisme]) (Nom "Agnolo Bronzino") (Nacionalitat "Itàlia") (TéÉpoca [RenaixementEpoca]))
([Leighton] of Pintor (TéEstils [Academicisme]) (Nom "Frederic Leighton") (Nacionalitat "Regne Unit") (TéÉpoca [Romantica]))
([Chardin] of Pintor (TéEstils [Rococo]) (Nom "Jean Siméon Chardin") (Nacionalitat "França") (TéÉpoca [Barroca]))
([Matisse] of Pintor (TéEstils [Fauvisme]) (Nom "Henri Matisse") (Nacionalitat "França") (TéÉpoca [Contemporanea]))
([Jacques] of Pintor (TéEstils [Neoclassic]) (Nom "Jacques-Louis David") (Nacionalitat "França") (TéÉpoca [Neoclassica]))
([Fragonard] of Pintor (TéEstils [Rococo]) (Nom "Jean-Honoré Fragonard") (Nacionalitat "França") (TéÉpoca [Neoclassica]))
([Morelli] of Pintor (TéEstils [Romanticisme] [Simbolisme]) (Nom "Domenico Morelli") (Nacionalitat "Itàlia") (TéÉpoca [Romantica]))
([Courbet] of Pintor (TéEstils [Realisme]) (Nom "Gustave Courbet") (Nacionalitat "França") (TéÉpoca [Romantica]))
([Franz] of Pintor (TéEstils [Expressionisme]) (Nom "Franz Marc") (Nacionalitat "Alemanya") (TéÉpoca [Moderna]))
([Ribera] of Pintor (TéEstils [Neoclassic]) (Nom "Juan Antonio Ribera") (Nacionalitat "Espanya") (TéÉpoca [Neoclassica]))
([Frida] of Pintor (TéEstils [Naif]) (Nom "Frida Kahlo") (Nacionalitat "Mèxic") (TéÉpoca [Contemporanea]))
([Rousseau] of Pintor (TéEstils [Naif]) (Nom "Henri Rousseau") (Nacionalitat "França") (TéÉpoca [Moderna]))
)

(definstances Obras
([ElGrito] of Obra (Nom "El grito") (Any 1893) (Dimensions 6688) (Rellevancia 8) (Complexitat 5) (Sala 6) (pintada_per [Munch]) (TéEstil [Expressionisme]) (TéTemàtica [Terror]) (TéÉpoca [Moderna]))
([AmorDolor] of Obra (Nom "Amor i Dolor") (Any 1895) (Dimensions 176) (Rellevancia 5) (Complexitat 7) (Sala 6) (pintada_per [Munch]) (TéEstil [Expressionisme]) (TéTemàtica [Terror]) (TéÉpoca [Moderna]))
([LaNocheEstrellada] of Obra (Nom "La Nit Estrellada") (Any 1889) (Dimensions 6788) (Rellevancia 9) (Complexitat 6) (Sala 6) (pintada_per [VanGogh]) (TéEstil [Postimpressionisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Moderna]))
([Guernica] of Obra (Nom "El Guernica") (Any 1937) (Dimensions 271266) (Rellevancia 9) (Complexitat 2) (Sala 7) (pintada_per [Picasso]) (TéEstil [Cubisme]) (TéTemàtica [Guerra]) (TéÉpoca [Contemporanea]))
([LesDemoiselles] of Obra (Nom "Les Demoiselles d'Avignon") (Any 1907) (Dimensions 57000) (Rellevancia 7) (Complexitat 2) (Sala 7) (pintada_per [Picasso]) (TéEstil [Cubisme]) (TéTemàtica [Retrat]) (TéÉpoca [Contemporanea]))
([ElJardin] of Obra (Nom "El Jardí de les delicies") (Any 1505) (Dimensions 85580) (Rellevancia 7) (Complexitat 9) (Sala 2) (pintada_per [ElBosco]) (TéEstil [Flamenc]) (TéTemàtica [Religio]) (TéÉpoca [RenaixementEpoca]))
([LaCreacionDeAdan] of Obra (Nom "La creació d'Adan") (Any 1511) (Dimensions 159600) (Rellevancia 8) (Complexitat 8) (Sala 2) (pintada_per [MiguelAngel]) (TéEstil [Renaixement]) (TéTemàtica [Religio]) (TéÉpoca [RenaixementEpoca]))
([NoiaPerla] of Obra (Nom "La noia de la perla") (Any 1665) (Dimensions 1860) (Rellevancia 9) (Complexitat 8) (Sala 3) (pintada_per [Vermeer]) (TéEstil [Barroc]) (TéTemàtica [Retrat]) (TéÉpoca [Barroca]))
([Xiquets] of Obra (Nom "Xiquets a la platja") (Any 1910) (Dimensions 21830) (Rellevancia 3) (Complexitat 7) (Sala 6) (pintada_per [Sorolla]) (TéEstil [Postimpressionisme]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Moderna]))
([TempestaNeu] of Obra (Nom "Tempesta de neu al mar") (Any 1842) (Dimensions 11163) (Rellevancia 4) (Complexitat 7) (Sala 5) (pintada_per [Turner]) (TéEstil [Romanticisme]) (TéTemàtica [Natura]) (TéÉpoca [Romantica]))
([MusicaTullerias] of Obra (Nom "La Música en las Tullerías") (Any 1862) (Dimensions 8968) (Rellevancia 5) (Complexitat 8) (Sala 6) (pintada_per [Manet]) (TéEstil [Impressionisme]) (TéTemàtica [Musica]) (TéÉpoca [Moderna]))
([SantJordi] of Obra (Nom "Sant Jordi i el drac") (Any 1505) (Dimensions 613) (Rellevancia 6) (Complexitat 7) (Sala 2) (pintada_per [Rafael]) (TéEstil [Renaixement]) (TéTemàtica [Mitologia]) (TéÉpoca [RenaixementEpoca]))
([TardaDiumenge] of Obra (Nom "Una tarda de diumenge a l'illa de la Grande Jatte") (Any 1884) (Dimensions 63940) (Rellevancia 8) (Complexitat 7) (Sala 6) (pintada_per [Seurat]) (TéEstil [Puntillisme]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Moderna]))
([PostaDeSol] of Obra (Nom "Posta de sol en un port") (Any 1645) (Dimensions 14008) (Rellevancia 4) (Complexitat 6) (Sala 3) (pintada_per [ClaudeLorrain]) (TéEstil [Classicisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Barroca]))
([ElCarnaval] of Obra (Nom "El carnaval d'Arlequí") (Any 1925) (Dimensions 5973) (Rellevancia 7) (Complexitat 2) (Sala 7) (pintada_per [Miro]) (TéEstil [Surrealisme]) (TéTemàtica [Abstracte]) (TéÉpoca [Contemporanea]))
([SolNaciente] of Obra (Nom "Impresión, sol naciente") (Any 1872) (Dimensions 3024) (Rellevancia 8) (Complexitat 9) (Sala 6) (pintada_per [Monet]) (TéEstil [Impressionisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Moderna]))
([MujerConSombrilla] of Obra (Nom "Mujer con sombrilla") (Any 1875) (Dimensions 8100) (Rellevancia 7) (Complexitat 9) (Sala 6) (pintada_per [Monet]) (TéEstil [Impressionisme]) (TéTemàtica [Retrat]) (TéÉpoca [Moderna]))
([LaTerraza] of Obra (Nom "La terraza de Saint-Adresse") (Any 1867) (Dimensions 12743) (Rellevancia 6) (Complexitat 9) (Sala 6) (pintada_per [Monet]) (TéEstil [Impressionisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Moderna]))
([ElFillHome] of Obra (Nom "El fill de l'home") (Any 1964) (Dimensions 10324) (Rellevancia 5) (Complexitat 4) (Sala 7) (pintada_per [Magritte]) (TéEstil [Surrealisme]) (TéTemàtica [Retrat]) (TéÉpoca [Contemporanea]))
([Parnas] of Obra (Nom "El Parnàs") (Any 1511) (Dimensions 35300) (Rellevancia 4) (Complexitat 7) (Sala 2) (pintada_per [Rafael]) (TéEstil [Renaixement]) (TéTemàtica [Mitologia]) (TéÉpoca [RenaixementEpoca]))
([ComposicioVIII] of Obra (Nom "Composició VIII") (Any 1923) (Dimensions 28140) (Rellevancia 8) (Complexitat 1) (Sala 7) (pintada_per [Kandinsky]) (TéEstil [EstilAbstracte]) (TéTemàtica [Musica]) (TéÉpoca [Contemporanea]))
([ElCavaller] of Obra (Nom "El cavaller, la mort i el diable") (Any 1513) (Dimensions 471) (Rellevancia 3) (Complexitat 6) (Sala 2) (pintada_per [Durero]) (TéEstil [Renaixement]) (TéTemàtica [Moral]) (TéÉpoca [RenaixementEpoca]))
([Primavera] of Obra (Nom "La primavera") (Any 1482) (Dimensions 63742) (Rellevancia 7) (Complexitat 7) (Sala 2) (pintada_per [Botticelli]) (TéEstil [EscolaFlorentina]) (TéTemàtica [Mitologia]) (TéÉpoca [RenaixementEpoca]))
([JoveCaptaire] of Obra (Nom "El jove captaire") (Any 1678) (Dimensions 13700) (Rellevancia 4) (Complexitat 6) (Sala 3) (pintada_per [Murillo]) (TéEstil [Barroc]) (TéTemàtica [Pobresa]) (TéÉpoca [Barroca]))
([SaturnDevorant] of Obra (Nom "Saturn devorant un fill") (Any 1823) (Dimensions 12118) (Rellevancia 8) (Complexitat 5) (Sala 4) (pintada_per [Goya]) (TéEstil [Romanticisme]) (TéTemàtica [Mitologia]) (TéÉpoca [Neoclassica]))
([PontLanglois] of Obra (Nom "El pont de Langlois") (Any 1888) (Dimensions 4386) (Rellevancia 4) (Complexitat 4) (Sala 6) (pintada_per [VanGogh]) (TéEstil [Postimpressionisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Moderna]))
([NitCafe] of Obra (Nom "El cafè de nit") (Any 1888) (Dimensions 6668) (Rellevancia 6) (Complexitat 5) (Sala 6) (pintada_per [VanGogh]) (TéEstil [Postimpressionisme]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Moderna]))
([LaPersistencia] of Obra (Nom "La persistència de la memòria") (Any 1931) (Dimensions 792) (Rellevancia 9) (Complexitat 8) (Sala 7) (pintada_per [Dali]) (TéEstil [Surrealisme]) (TéTemàtica [Temps]) (TéÉpoca [Contemporanea]))
([CristoDeSanJuan] of Obra (Nom "Cristo de San Juan de la Cruz") (Any 1951) (Dimensions 23780) (Rellevancia 4) (Complexitat 6) (Sala 7) (pintada_per [Dali]) (TéEstil [Surrealisme]) (TéTemàtica [Religio]) (TéÉpoca [Contemporanea]))
([RendicioBreda] of Obra (Nom "La rendició de Breda") (Any 1635) (Dimensions 112669) (Rellevancia 5) (Complexitat 7) (Sala 3) (pintada_per [Velazquez]) (TéEstil [Barroc]) (TéTemàtica [Historia]) (TéÉpoca [Barroca]))
([ElenaRoses] of Obra (Nom "Elena entre roses") (Any 1907) (Dimensions 8968) (Rellevancia 2) (Complexitat 6) (Sala 6) (pintada_per [Sorolla]) (TéEstil [Postimpressionisme]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Moderna]))
([LlunaVerda] of Obra (Nom "Lluna verda") (Any 1972) (Dimensions 884) (Rellevancia 4) (Complexitat 1) (Sala 7) (pintada_per [Miró]) (TéEstil [Surrealisme]) (TéTemàtica [Abstracte]) (TéÉpoca [Contemporanea]))
([VistaCanal] of Obra (Nom "Vista del gran canal mirant cap a la Punta della Dogana desde Caompo Sant'Ivo") (Any 1745) (Dimensions 3710) (Rellevancia 5) (Complexitat 6) (Sala 3) (pintada_per [Canaletto]) (TéEstil [Rococo]) (TéTemàtica [Paisatge]) (TéÉpoca [Barroca]))
([CaçaNeu] of Obra (Nom "Els caçadors en la neu") (Any 1565) (Dimensions 18954) (Rellevancia 5) (Complexitat 5) (Sala 2) (pintada_per [Bruegel]) (TéEstil [Flamenc]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [RenaixementEpoca]))
([AlegoriaAmor] of Obra (Nom "Alegoria del amor") (Any 1545) (Dimensions 16976) (Rellevancia 4) (Complexitat 6) (Sala 2) (pintada_per [Bronzino]) (TéEstil [Manierisme]) (TéTemàtica [Amor]) (TéÉpoca [RenaixementEpoca]))
([NaturaMort] of Obra (Nom "Natura morta amb pomes") (Any 1890) (pintada_per [Cezanne]) (Dimensions 1626) (Rellevancia 2) (Complexitat 4) (Sala 6) (TéEstil [Postimpressionisme]) (TéTemàtica [NaturaMorta]) (TéÉpoca [Moderna]))
([JunioArdiente] of Obra (Nom "Campament nocturn a Egipte") (Any 1869) (Dimensions 14184) (Rellevancia 4) (Complexitat 6) (Sala 4) (pintada_per [Leighton]) (TéEstil [Academicisme]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Neoclassica]))
([Banyistes] of Obra (Nom "Les grans banyistes") (Any 1906) (pintada_per [Cezanne]) (Dimensions 52793) (Rellevancia 4) (Complexitat 3) (Sala 6) (TéEstil [Postimpressionisme]) (TéTemàtica [Retrat]) (TéÉpoca [Moderna]))
([EnsenyançaMare] of Obra (Nom "L'ensenyança de la mare") (Any 1740) (Dimensions 1911) (Rellevancia 4) (Complexitat 6) (Sala 3) (pintada_per [Chardin]) (TéEstil [Rococo]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Barroca]))
([Golconda] of Obra (Nom "Golconda") (Any 1953) (Dimensions 8100) (Rellevancia 5) (Complexitat 5) (Sala 7) (pintada_per [Magritte]) (TéEstil [Surrealisme]) (TéTemàtica [Societat]) (TéÉpoca [Contemporanea]))
([ElCirc] of Obra (Nom "El circ") (Any 1891) (Dimensions 26640) (Rellevancia 4) (Complexitat 6) (Sala 6) (pintada_per [Seurat]) (TéEstil [Puntillisme]) (TéTemàtica [Espectacle]) (TéÉpoca [Moderna]))
([Waterloo] of Obra (Nom "El camp de Waterloo") (Any 1818) (Dimensions 35252) (Rellevancia 6) (Complexitat 6) (Sala 5) (pintada_per [Turner]) (TéEstil [Romanticisme]) (TéTemàtica [Guerra]) (TéÉpoca [Romantica]))
([ElPeto] of Obra (Nom "El petó") (Any 1909) (Dimensions 32400) (Rellevancia 8) (Complexitat 3) (Sala 7) (pintada_per [Klimt]) (TéEstil [Simbolisme]) (TéTemàtica [Amor]) (TéÉpoca [Contemporanea]))
([VergeMaria] of Obra (Nom "Verge Maria") (Any 1597) (Dimensions 2132) (Rellevancia 3) (Complexitat 5) (Sala 2) (pintada_per [ElGreco]) (TéEstil [Manierisme]) (TéTemàtica [Religio]) (TéÉpoca [RenaixementEpoca]))
([Danae] of Obra (Nom "Dánae") (Any 1636) (Dimensions 37555) (Rellevancia 4) (Complexitat 6) (Sala 3) (pintada_per [Rembrandt]) (TéEstil [Barroc]) (TéTemàtica [Mitologia]) (TéÉpoca [Barroca]))
([Verd] of Obra (Nom "Verd") (Any 1931) (Dimensions 37555) (Rellevancia 4) (Complexitat 2) (Sala 7) (pintada_per [Kandinsky]) (TéEstil [EstilAbstracte]) (TéTemàtica [Abstracte]) (TéÉpoca [Contemporanea]))
([FlorersVermells] of Obra (Nom "Florers vermells i taronja") (Any 1907) (Dimensions 39600) (Rellevancia 4) (Complexitat 3) (Sala 7) (pintada_per [Matisse]) (TéEstil [Fauvisme]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Contemporanea]))
([FugaEgipte] of Obra (Nom "Fuga a Egipte") (Any 1563) (Dimensions 2062) (Rellevancia 4) (Complexitat 7) (Sala 2) (pintada_per [Bruegel]) (TéEstil [Renaixement]) (TéTemàtica [Religio]) (TéÉpoca [RenaixementEpoca]))
([PenyaSegats] of Obra (Nom "Penya-segats blancs a Rügen") (Any 1818) (Dimensions 6425) (Rellevancia 5) (Complexitat 6) (Sala 5) (pintada_per [Friedrich]) (TéEstil [Romanticisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Romantica]))
([ElCaminante] of Obra (Nom "El caminante sobre el mar de nubes") (Any 1818) (Dimensions 7091) (Rellevancia 8) (Complexitat 8) (Sala 5) (pintada_per [Friedrich]) (TéEstil [Romanticisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Romantica]))
([Pacient] of Obra (Nom "El pacient") (Any 1914) (Dimensions 928) (Rellevancia 2) (Complexitat 3) (Sala 7) (pintada_per [Hodler]) (TéEstil [Simbolisme]) (TéTemàtica [Retrat]) (TéÉpoca [Contemporanea]))
([DonaPlora] of Obra (Nom "La dona que plora") (Any 1937) (Dimensions 3050) (Rellevancia 4) (Complexitat 2) (Sala 7) (pintada_per [Picasso]) (TéEstil [Cubisme]) (TéTemàtica [Retrat]) (TéÉpoca [Contemporanea]))
([MortVida] of Obra (Nom "Mort i Vida") (Any 1915) (Dimensions 360) (Rellevancia 6) (Complexitat 5) (Sala 7) (pintada_per [Klimt]) (TéEstil [Simbolisme]) (TéTemàtica [Mort]) (TéÉpoca [Contemporanea]))
([InfantaMargarita] of Obra (Nom "La Infanta Margarita en blau") (Any 1659) (Dimensions 13589) (Rellevancia 5) (Complexitat 7) (Sala 3) (pintada_per [Velazquez]) (TéEstil [Barroc]) (TéTemàtica [Retrat]) (TéÉpoca [Barroca]))
([TresMaig] of Obra (Nom "El tres de maig a Madrid") (Any 1814) (Dimensions 92996) (Rellevancia 8) (Complexitat 6) (Sala 4) (pintada_per [Goya]) (TéEstil [Romanticisme]) (TéTemàtica [Guerra]) (TéÉpoca [Neoclassica]))
([TentacioCrist] of Obra (Nom "La tentació de Crist") (Any 1500) (Dimensions 191752) (Rellevancia 4) (Complexitat 7) (Sala 2) (pintada_per [Botticelli]) (TéEstil [EscolaFlorentina]) (TéTemàtica [Religio]) (TéÉpoca [RenaixementEpoca]))
([PlujaVapor] of Obra (Nom "Pluja, vapor i velocitat. El gran ferrocarril de l'oest") (Any 1844) (Dimensions 11083) (Rellevancia 3) (Complexitat 4) (Sala 5) (pintada_per [Turner]) (TéEstil [Romanticisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Romantica]))
([Girasols] of Obra (Nom "Els gira-sols") (Any 1888) (pintada_per [VanGogh]) (Dimensions 6696) (Rellevancia 8) (Complexitat 5) (Sala 6) (TéEstil [Postimpressionisme]) (TéTemàtica [Floral]) (TéÉpoca [Moderna]))
([Verge] of Obra (Nom "Verge en Majestat") (Any 1286) (Dimensions 85855) (Rellevancia 3) (Complexitat 4) (Sala 1) (pintada_per [Cimabue]) (TéEstil [Gotic]) (TéTemàtica [Religio]) (TéÉpoca [EdatMitjana]))
([ElJudiciFinal] of Obra (Nom "El judici final") (Any 1306) (Dimensions 840000) (Rellevancia 5) (Complexitat 6) (Sala 1) (pintada_per [Giotto]) (TéEstil [Gotic]) (TéTemàtica [Religio]) (TéÉpoca [EdatMitjana]))
([Madonna] of Obra (Nom "Madonna Rucellai") (Any 1285) (Dimensions 130500) (Rellevancia 5) (Complexitat 4) (Sala 1) (pintada_per [Duccio]) (TéEstil [Gotic]) (TéTemàtica [Religio]) (TéÉpoca [EdatMitjana]))
([AbsideSanCliment] of Obra (Nom "Àbside de San Climent de Tahull") (Any 1133) (Dimensions 223200) (Rellevancia 6) (Complexitat 4) (Sala 1) (pintada_per [MestreTahull]) (TéEstil [Romanic]) (TéTemàtica [Religio]) (TéÉpoca [EdatMitjana]))
([AbsideSantaMaria] of Obra (Nom "Àbside de Santa Maria de Tahull") (Any 1123) (Dimensions 154200) (Rellevancia 4) (Complexitat 4) (Sala 1) (pintada_per [MestreTahull]) (TéEstil [Romanic]) (TéTemàtica [Religio]) (TéÉpoca [EdatMitjana]))
([LaLibertat] of Obra (Nom "La libertad guiando al pueblo") (Any 1830) (Dimensions 84500) (Rellevancia 9) (Complexitat 7) (Sala 6) (pintada_per [Delacroix]) (TéEstil [Romanticisme]) (TéTemàtica [Guerra]) (TéÉpoca [Moderna]))
([ElAngel] of Obra (Nom "El ángel caído") (Any 1847) (Dimensions 23678) (Rellevancia 7) (Complexitat 9) (Sala 6) (pintada_per [Cabanel]) (TéEstil [Academicisme]) (TéTemàtica [Religio]) (TéÉpoca [Moderna]))
([LaUltimaCena] of Obra (Nom "L'últim sopar") (Any 1498) (Dimensions 23678) (Rellevancia 8) (Complexitat 7) (Sala 2) (pintada_per [DaVinci]) (TéEstil [Renaixement]) (TéTemàtica [Religio]) (TéÉpoca [RenaixementEpoca]))
([LaGioconda] of Obra (Nom "La Gioconda") (Any 1519) (Dimensions 4187) (Rellevancia 10) (Complexitat 8) (Sala 2) (pintada_per [DaVinci]) (TéEstil [Renaixement]) (TéTemàtica [Retrat]) (TéÉpoca [RenaixementEpoca]))
([LesMeninas] of Obra (Nom "Les meninas") (Any 1656) (Dimensions 90221) (Rellevancia 9) (Complexitat 8) (Sala 3) (pintada_per [Velazquez]) (TéEstil [Barroc]) (TéTemàtica [Retrat]) (TéÉpoca [Barroca]))
([TresMusics] of Obra (Nom "Tres músics") (Any 1921) (Dimensions 44736) (Rellevancia 6) (Complexitat 2) (Sala 7) (pintada_per [Picasso]) (TéEstil [Cubisme]) (TéTemàtica [Musica]) (TéÉpoca [Contemporanea]))
([LaMatança] of Obra (Nom "La matança de Quíos") (Any 1824) (Dimensions 147618) (Rellevancia 5) (Complexitat 7) (Sala 6) (pintada_per [Delacroix]) (TéEstil [Romanticisme]) (TéTemàtica [Guerra]) (TéÉpoca [Moderna]))
([Autoretrat] of Obra (Nom "Autoretrat") (Any 1887) (Dimensions 1415) (Rellevancia 6) (Complexitat 5) (Sala 6) (pintada_per [VanGogh]) (TéEstil [Postimpressionisme]) (TéTemàtica [Retrat]) (TéÉpoca [Moderna]))
([Composicio] of Obra (Nom "Composició amb vermell, blau i groc") (Any 1921) (Dimensions 2025) (Rellevancia 8) (Complexitat 1) (Sala 7) (pintada_per [Mondrian]) (TéEstil [NeoPlasticisme]) (TéTemàtica [Abstracte]) (TéÉpoca [Contemporanea]))
([VenusDelEspejo] of Obra (Nom "Venus del Espejo") (Any 1651) (Dimensions 21594) (Rellevancia 5) (Complexitat 8) (Sala 3) (pintada_per [Velazquez]) (TéEstil [Barroc]) (TéTemàtica [Mitologia]) (TéÉpoca [Barroca]))
([LaTrinidad] of Obra (Nom "La Trinidad") (Any 1577) (Dimensions 53700) (Rellevancia 6) (Complexitat 7) (Sala 2) (pintada_per [ElGreco]) (TéEstil [Manierisme]) (TéTemàtica [Religio]) (TéÉpoca [RenaixementEpoca]))
([ElNacimientoDeVenus] of Obra (Nom "El nacimiento de Venus") (Any 1485) (Dimensions 48041) (Rellevancia 7) (Complexitat 7) (Sala 2) (pintada_per [Botticelli]) (TéEstil [EscolaFlorentina]) (TéTemàtica [Mitologia]) (TéÉpoca [RenaixementEpoca]))
([Juramento] of Obra (Nom "El jurament dels Horacis") (Any 1784) (Dimensions 140250) (Rellevancia 8) (Complexitat 7) (Sala 4) (pintada_per [Jacques]) (TéEstil [Neoclassic]) (TéTemàtica [Historia]) (TéÉpoca [Neoclassica]))
([MortSocrates] of Obra (Nom "La mort de Sòcrates") (Any 1787) (Dimensions 25408) (Rellevancia 6) (Complexitat 7) (Sala 4) (pintada_per [Jacques]) (TéEstil [Neoclassic]) (TéTemàtica [Historia]) (TéÉpoca [Neoclassica]))
([MarteVenus] of Obra (Nom "Mart desarmat per Venus y les Gràcies") (Any 1824) (Dimensions 81620) (Rellevancia 4) (Complexitat 7) (Sala 4) (pintada_per [Jacques]) (TéEstil [Neoclassic]) (TéTemàtica [Mitologia]) (TéÉpoca [Neoclassica]))
([NaturaFlors] of Obra (Nom "Natura Morta, gerra amb flors") (Any 1763) (Dimensions 81620) (Rellevancia 2) (Complexitat 7) (Sala 4) (pintada_per [Chardin]) (TéEstil [Rococo]) (TéTemàtica [Floral]) (TéÉpoca [Neoclassica]))
([Columpi] of Obra (Nom "El columpi") (Any 1767) (Dimensions 5265) (Rellevancia 8) (Complexitat 9) (Sala 4) (pintada_per [Fragonard]) (TéEstil [Rococo]) (TéTemàtica [Natura]) (TéÉpoca [Neoclassica]))
([ElPetoRobat] of Obra (Nom "El petó robat") (Any 1790) (Dimensions 2475) (Rellevancia 5) (Complexitat 7) (Sala 4) (pintada_per [Fragonard]) (TéEstil [Rococo]) (TéTemàtica [Amor]) (TéÉpoca [Neoclassica]))
([AutoretratDaVinci] of Obra (Nom "Autoretrat (DaVinci)") (Any 1513) (Dimensions 713) (Rellevancia 7) (Complexitat 6) (Sala 2) (pintada_per [DaVinci]) (TéEstil [Renaixement]) (TéTemàtica [Retrat]) (TéÉpoca [RenaixementEpoca]))
([BoogieWoogie] of Obra (Nom "Broadway Boogie-Woogie") (Any 1943) (Dimensions 16129) (Rellevancia 5) (Complexitat 2) (Sala 7) (pintada_per [Mondrian]) (TéEstil [NeoPlasticisme]) (TéTemàtica [Abstracte]) (TéÉpoca [Contemporanea]))
([Elefants] of Obra (Nom "Els elefants") (Any 1948) (Dimensions 2940) (Rellevancia 5) (Complexitat 6) (Sala 7) (pintada_per [Dali]) (TéEstil [Surrealisme]) (TéTemàtica [Animals]) (TéÉpoca [Contemporanea]))
([Nighthawks] of Obra (Nom "Nighthawks") (Any 1942) (Dimensions 2940) (Rellevancia 4) (Complexitat 6) (Sala 7) (pintada_per [Hopper]) (TéEstil [Realisme]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Contemporanea]))
([NoiaCosint] of Obra (Nom "Noia cosint") (Any 1921) (Dimensions 2222) (Rellevancia 4) (Complexitat 4) (Sala 7) (pintada_per [Hopper]) (TéEstil [Realisme]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Contemporanea]))
([PasiajePsique] of Obra (Nom "Paisatge amb Psique a l'exterior del palau de Cupit") (Any 1664) (Dimensions 13137) (Rellevancia 3) (Complexitat 5) (Sala 3) (pintada_per [Lorrain]) (TéEstil [Classicisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Barroca]))
([NaixementMon] of Obra (Nom "El naixement del món") (Any 1925) (Dimensions 50160) (Rellevancia 5) (Complexitat 2) (Sala 7) (pintada_per [Miro]) (TéEstil [Surrealisme]) (TéTemàtica [Abstracte]) (TéÉpoca [Contemporanea]))
([ElionorToledo] of Obra (Nom "Elionor de Toledo amb el seu fill") (Any 1545) (Dimensions 11040) (Rellevancia 5) (Complexitat 7) (Sala 2) (pintada_per [Bronzino]) (TéEstil [Manierisme]) (TéTemàtica [Retrat]) (TéÉpoca [RenaixementEpoca]))
([LlunaDeMel] of Obra (Nom "La Lluna de mel del pintor") (Any 1869) (Dimensions 6435) (Rellevancia 4) (Complexitat 7) (Sala 5) (pintada_per [Leighton]) (TéEstil [Academicisme]) (TéTemàtica [Amor]) (TéÉpoca [Romantica]))
([Flagelacio] of Obra (Nom "La flagel·lació de Crist") (Any 1280) (Dimensions 494) (Rellevancia 4) (Complexitat 3) (Sala 1) (pintada_per [Cimabue]) (TéEstil [Gotic]) (TéTemàtica [Religio]) (TéÉpoca [EdatMitjana]))
([AngelMort] of Obra (Nom "L'àngel de la mort") (Any 1897) (Dimensions 17280) (Rellevancia 5) (Complexitat 7) (Sala 5) (pintada_per [Morelli]) (TéEstil [Simbolisme]) (TéTemàtica [Mort]) (TéÉpoca [Romantica]))
([NoiaPaons] of Obra (Nom "Noia amb paoms morts") (Any 1639) (Dimensions 19647) (Rellevancia 3) (Complexitat 6) (Sala 3) (pintada_per [Rembrandt]) (TéEstil [Barroc]) (TéTemàtica [NaturaMorta]) (TéÉpoca [Barroca]))
([CopaPlata] of Obra (Nom "La copa de plata") (Any 1740) (Dimensions 1911) (Rellevancia 2) (Complexitat 5) (Sala 3) (pintada_per [Chardin]) (TéEstil [Rococo]) (TéTemàtica [NaturaMorta]) (TéÉpoca [Barroca]))
([Dança] of Obra (Nom "La dança") (Any 1910) (Dimensions 39600) (Rellevancia 7) (Complexitat 3) (Sala 7) (pintada_per [Matisse]) (TéEstil [Fauvisme]) (TéTemàtica [Musica]) (TéÉpoca [Contemporanea]))
([Composicio2] of Obra (Nom "Composició amb gris i marró fluix") (Any 1918) (Dimensions 4002) (Rellevancia 3) (Complexitat 1) (Sala 7) (pintada_per [Mondrian]) (TéEstil [NeoPlasticisme]) (TéTemàtica [Abstracte]) (TéÉpoca [Contemporanea]))
([DonaLloro] of Obra (Nom "Dona amb lloro") (Any 1866) (Dimensions 25330) (Rellevancia 6) (Complexitat 8) (Sala 5) (pintada_per [Courbet]) (TéEstil [Realisme]) (TéTemàtica [Erotisme]) (TéÉpoca [Romantica]))
([Enterrament] of Obra (Nom "Enterrament a Ornans") (Any 1849) (Dimensions 210420) (Rellevancia 6) (Complexitat 7) (Sala 5) (pintada_per [Courbet]) (TéEstil [Realisme]) (TéTemàtica [Mort]) (TéÉpoca [Romantica]))
([DonaReclinada] of Obra (Nom "Dona reclinada") (Any 1865) (Dimensions 9856) (Rellevancia 4) (Complexitat 5) (Sala 5) (pintada_per [Courbet]) (TéEstil [Realisme]) (TéTemàtica [Erotisme]) (TéÉpoca [Romantica]))
([Comics] of Obra (Nom "Còmics ambulants") (Any 1793) (Dimensions 1344) (Rellevancia 4) (Complexitat 6) (Sala 4) (pintada_per [Goya]) (TéEstil [Neoclassic]) (TéTemàtica [Espectacle]) (TéÉpoca [Neoclassica]))
([LaMaja] of Obra (Nom "La maja nua") (Any 1797) (Dimensions 18430) (Rellevancia 7) (Complexitat 7) (Sala 4) (pintada_per [Goya]) (TéEstil [Romanticisme]) (TéTemàtica [Erotisme]) (TéÉpoca [Neoclassica]))
([Temptacions] of Obra (Nom "Les temptacions de Sant Antoni") (Any 1946) (Dimensions 10800) (Rellevancia 5) (Complexitat 5) (Sala 7) (pintada_per [Dali]) (TéEstil [Surrealisme]) (TéTemàtica [Religio]) (TéÉpoca [Contemporanea]))
([TorreCavalls] of Obra (Nom "La torre dels cavalls blaus") (Any 1913) (Dimensions 26000) (Rellevancia 6) (Complexitat 3) (Sala 6) (pintada_per [Franz]) (TéEstil [Expressionisme]) (TéTemàtica [Animals]) (TéÉpoca [Moderna]))
([Guineus] of Obra (Nom "Les guineus") (Any 1913) (Dimensions 5808) (Rellevancia 5) (Complexitat 4) (Sala 6) (pintada_per [Franz]) (TéEstil [Expressionisme]) (TéTemàtica [Animals]) (TéÉpoca [Moderna]))
([Tigres] of Obra (Nom "Un tigre jove jugant amb la seva mare") (Any 1830) (Dimensions 25479) (Rellevancia 4) (Complexitat 7) (Sala 6) (pintada_per [Delacroix]) (TéEstil [Romanticisme]) (TéTemàtica [Animals]) (TéÉpoca [Moderna]))
([RamFlors] of Obra (Nom "Ram de flors") (Any 1904) (pintada_per [Cezanne]) (Dimensions 4928) (Rellevancia 2) (Complexitat 5) (Sala 6) (TéEstil [Postimpressionisme]) (TéTemàtica [Floral]) (TéÉpoca [Moderna]))
([Sibila] of Obra (Nom "La Sibil·la Dèlfica") (Any 1500) (Dimensions 159600) (Rellevancia 8) (Complexitat 8) (Sala 2) (pintada_per [MiguelAngel]) (TéEstil [Renaixement]) (TéTemàtica [Mitologia]) (TéÉpoca [RenaixementEpoca]))
([Cincinato] of Obra (Nom "Cincinato abandona l'arada per dictar lleis a Roma") (Any 1806) (Dimensions 34400) (Rellevancia 5) (Complexitat 7) (Sala 4) (pintada_per [Ribera]) (TéEstil [Neoclassic]) (TéTemàtica [Historia]) (TéÉpoca [Neoclassica]))
([Wamba] of Obra (Nom "Wamba renuncia a la corona") (Any 1819) (Dimensions 34400) (Rellevancia 6) (Complexitat 7) (Sala 4) (pintada_per [Ribera]) (TéEstil [Neoclassic]) (TéTemàtica [Historia]) (TéÉpoca [Neoclassica]))
([AlegoriaEstiu] of Obra (Nom "Alegoria a l'Estiu") (Any 1819) (Dimensions 4698) (Rellevancia 6) (Complexitat 8) (Sala 4) (pintada_per [Ribera]) (TéEstil [Neoclassic]) (TéTemàtica [Religio]) (TéÉpoca [Neoclassica]))
([Lletera] of Obra (Nom "La lletera") (Any 1665) (Dimensions 1865) (Rellevancia 7) (Complexitat 8) (Sala 3) (pintada_per [Vermeer]) (TéEstil [Barroc]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Barroca]))
([ArtPintura] of Obra (Nom "L'art de la pintura'") (Any 1666) (Dimensions 12000) (Rellevancia 6) (Complexitat 7) (Sala 3) (pintada_per [Vermeer]) (TéEstil [Barroc]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Barroca]))
([Embarcament] of Obra (Nom "Paisatge amb l'embarcament en Òstia de Santa Paula Romana") (Any 1640) (Dimensions 30595) (Rellevancia 4) (Complexitat 8) (Sala 3) (pintada_per [Lorrain]) (TéEstil [Classicisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Barroca]))
([Pecats] of Obra (Nom "Taula dels set pecats capitals") (Any 1510) (Dimensions 16670) (Rellevancia 6) (Complexitat 7) (Sala 2) (pintada_per [ElBosco]) (TéEstil [Flamenc]) (TéTemàtica [Moral]) (TéÉpoca [RenaixementEpoca]))
([Babel] of Obra (Nom "La torre de Babel") (Any 1565) (Dimensions 17556) (Rellevancia 6) (Complexitat 7) (Sala 2) (pintada_per [Bruegel]) (TéEstil [Flamenc]) (TéTemàtica [Religio]) (TéÉpoca [RenaixementEpoca]))
([Gerra] of Obra (Nom "Gerra de flors") (Any 1881) (Dimensions 1782) (Rellevancia 2) (Complexitat 5) (Sala 6) (pintada_per [Seurat]) (TéEstil [Puntillisme]) (TéTemàtica [Floral]) (TéÉpoca [Moderna]))
([ComposicioVII] of Obra (Nom "Composició VII") (Any 1913) (Dimensions 60621) (Rellevancia 7) (Complexitat 3) (Sala 7) (pintada_per [Kandinsky]) (TéEstil [EstilAbstracte]) (TéTemàtica [Abstracte]) (TéÉpoca [Contemporanea]))
([NensMenjant] of Obra (Nom "Nens menjant raïm i meló") (Any 1678) (Dimensions 15084) (Rellevancia 4) (Complexitat 6) (Sala 3) (pintada_per [Murillo]) (TéEstil [Barroc]) (TéTemàtica [Pobresa]) (TéÉpoca [Barroca]))
([Desintegracio] of Obra (Nom "La desintegració de la persistència de la memòria") (Any 1954) (Dimensions 838) (Rellevancia 6) (Complexitat 6) (Sala 7) (pintada_per [Dali]) (TéEstil [Surrealisme]) (TéTemàtica [Temps]) (TéÉpoca [Contemporanea]))
([Masia] of Obra (Nom "La masia") (Any 1922) (Dimensions 17492) (Rellevancia 4) (Complexitat 3) (Sala 7) (pintada_per [Miro]) (TéEstil [Surrealisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Contemporanea]))
([Concurs] of Obra (Nom "El concurs musical") (Any 1755) (Dimensions 4588) (Rellevancia 4) (Complexitat 7) (Sala 4) (pintada_per [Fragonard]) (TéEstil [Rococo]) (TéTemàtica [Musica]) (TéÉpoca [Neoclassica]))
([Ansietat] of Obra (Nom "Ansietat") (Any 1894) (Dimensions 6956) (Rellevancia 5) (Complexitat 4) (Sala 6) (pintada_per [Munch]) (TéEstil [Expressionisme]) (TéTemàtica [Terror]) (TéÉpoca [Moderna]))
([Peto] of Obra (Nom "El petó (Munch)") (Any 1897) (Dimensions 8019) (Rellevancia 4) (Complexitat 4) (Sala 6) (pintada_per [Munch]) (TéEstil [Expressionisme]) (TéTemàtica [Amor]) (TéÉpoca [Moderna]))
([Automat] of Obra (Nom "Automat") (Any 1927) (Dimensions 6347) (Rellevancia 2) (Complexitat 5) (Sala 7) (pintada_per [Hopper]) (TéEstil [Realisme]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Contemporanea]))
([DosFridas] of Obra (Nom "Les dos Fridas") (Any 1939) (Dimensions 30015) (Rellevancia 7) (Complexitat 5) (Sala 7) (pintada_per [Frida]) (TéEstil [Naif]) (TéTemàtica [Retrat]) (TéÉpoca [Contemporanea]))
([Pitahaies] of Obra (Nom "Pitahaies") (Any 1938) (Dimensions 1488) (Rellevancia 5) (Complexitat 5) (Sala 7) (pintada_per [Frida]) (TéEstil [Naif]) (TéTemàtica [NaturaMorta]) (TéÉpoca [Contemporanea]))
([AutoretratMico] of Obra (Nom "Autoretrat amb mico") (Any 1938) (Dimensions 1238) (Rellevancia 6) (Complexitat 4) (Sala 7) (pintada_per [Frida]) (TéEstil [Naif]) (TéTemàtica [Retrat]) (TéÉpoca [Contemporanea]))
([TigreTormenta] of Obra (Nom "Tigre en una tormenta tropical") (Any 1891) (Dimensions 21060) (Rellevancia 6) (Complexitat 3) (Sala 6) (pintada_per [Rousseau]) (TéEstil [Naif]) (TéTemàtica [Natura]) (TéÉpoca [Moderna]))
([Alger] of Obra (Nom "Paisatge en Alger") (Any 1880) (Dimensions 2298) (Rellevancia 3) (Complexitat 4) (Sala 6) (pintada_per [Rousseau]) (TéEstil [Naif]) (TéTemàtica [Paisatge]) (TéÉpoca [Moderna]))
([JardiGiverny] of Obra (Nom "El jardí de l'artista en Giverny") (Any 1900) (Dimensions 7556) (Rellevancia 5) (Complexitat 8) (Sala 6) (pintada_per [Monet]) (TéEstil [Impressionisme]) (TéTemàtica [Floral]) (TéÉpoca [Moderna]))
([Napoleo] of Obra (Nom "Napoleó creuant els Alps") (Any 1811) (Dimensions 57460) (Rellevancia 9) (Complexitat 8) (Sala 4) (pintada_per [Jacques]) (TéEstil [Neoclassic]) (TéTemàtica [Historia]) (TéÉpoca [Neoclassica]))
([RondaNit] of Obra (Nom "La ronda de nit") (Any 1642) (Dimensions 157242) (Rellevancia 7) (Complexitat 6) (Sala 3) (pintada_per [Rembrandt]) (TéEstil [Barroc]) (TéTemàtica [VidaQuotidiana]) (TéÉpoca [Barroca]))
([DosVells] of Obra (Nom "Dos Vells") (Any 1823) (Dimensions 9504) (Rellevancia 5) (Complexitat 4) (Sala 4) (pintada_per [Goya]) (TéEstil [Romanticisme]) (TéTemàtica [Pobresa]) (TéÉpoca [Neoclassica]))
([DuquesaAlba] of Obra (Nom "La Duquesa de Alba de blanc") (Any 1795) (Dimensions 24768) (Rellevancia 4) (Complexitat 5) (Sala 4) (pintada_per [Goya]) (TéEstil [Romanticisme]) (TéTemàtica [Retrat]) (TéÉpoca [Neoclassica]))
([Amapoles] of Obra (Nom "Amapoles") (Any 1873) (Dimensions 3250) (Rellevancia 8) (Complexitat 7) (Sala 6) (pintada_per [Monet]) (TéEstil [Impressionisme]) (TéTemàtica [Paisatge]) (TéÉpoca [Moderna]))
([LesBanyistes] of Obra (Nom "Les banyistes") (Any 1865) (Dimensions 43811) (Rellevancia 6) (Complexitat 6) (Sala 5) (pintada_per [Courbet]) (TéEstil [Realisme]) (TéTemàtica [Erotisme]) (TéÉpoca [Romantica]))
([VergeRoques] of Obra (Nom "Verge de les roques") (Any 1486) (Dimensions 24278) (Rellevancia 4) (Complexitat 6) (Sala 2) (pintada_per [DaVinci]) (TéEstil [Renaixement]) (TéTemàtica [Religio]) (TéÉpoca [RenaixementEpoca]))
([Buffet] of Obra (Nom "El buffet") (Any 1728) (Dimensions 25026) (Rellevancia 5) (Complexitat 6) (Sala 3) (pintada_per [Chardin]) (TéEstil [Rococo]) (TéTemàtica [NaturaMorta]) (TéÉpoca [Barroca]))
([Calumnia] of Obra (Nom "La calumnia de Apeles") (Any 1495) (Dimensions 5642) (Rellevancia 5) (Complexitat 7) (Sala 2) (pintada_per [Botticelli]) (TéEstil [EscolaFlorentina]) (TéTemàtica [Historia]) (TéÉpoca [RenaixementEpoca]))
([Paralitzat] of Obra (Nom "Temps paralitzat") (Any 1938) (Dimensions 14508) (Rellevancia 3) (Complexitat 5) (Sala 7) (pintada_per [Magritte]) (TéEstil [Surrealisme]) (TéTemàtica [Temps]) (TéÉpoca [Contemporanea]))
([EscolaAtenes] of Obra (Nom "L'escola d'Atenes") (Any 1511) (Dimensions 385000) (Rellevancia 9) (Complexitat 8) (Sala 2) (pintada_per [Rafael]) (TéEstil [Renaixement]) (TéTemàtica [Societat]) (TéÉpoca [RenaixementEpoca]))
([TresEdats] of Obra (Nom "Les tres edats de la dona") (Any 1905) (Dimensions 32400) (Rellevancia 4) (Complexitat 2) (Sala 7) (pintada_per [Klimt]) (TéEstil [Simbolisme]) (TéTemàtica [Temps]) (TéÉpoca [Contemporanea]))
([Llebre] of Obra (Nom "La llebre") (Any 1502) (Dimensions 567) (Rellevancia 3) (Complexitat 8) (Sala 2) (pintada_per [Durero]) (TéEstil [Renaixement]) (TéTemàtica [Animals]) (TéÉpoca [RenaixementEpoca]))
([Resurreccio] of Obra (Nom "La resurrecció de Llàtzer") (Any 1310) (Dimensions 2018) (Rellevancia 4) (Complexitat 4) (Sala 1) (pintada_per [Duccio]) (TéEstil [Gotic]) (TéTemàtica [Religio]) (TéÉpoca [EdatMitjana]))
([Lamentacio] of Obra (Nom "Lamentació sobre Crist mort") (Any 1305) (Dimensions 37000) (Rellevancia 3) (Complexitat 3) (Sala 1) (pintada_per [Giotto]) (TéEstil [Gotic]) (TéTemàtica [Religio]) (TéÉpoca [EdatMitjana]))
([Costurera] of Obra (Nom "La costurera") (Any 1643) (Dimensions 4440) (Rellevancia 5) (Complexitat 7) (Sala 3) (pintada_per [Velazquez]) (TéEstil [Barroc]) (TéTemàtica [Retrat]) (TéÉpoca [Barroca]))
([VellGuitarrista] of Obra (Nom "El vell guitarrista ceg") (Any 1903) (Dimensions 11011) (Rellevancia 7) (Complexitat 4) (Sala 7) (pintada_per [Picasso]) (TéEstil [Expressionisme]) (TéTemàtica [Retrat]) (TéÉpoca [Contemporanea]))
([Plaza] of Obra (Nom "Plaza de Sant Marcos") (Any 1724) (Dimensions 29110) (Rellevancia 5) (Complexitat 7) (Sala 3) (pintada_per [Canaletto]) (TéEstil [Rococo]) (TéTemàtica [Paisatge]) (TéÉpoca [Barroca]))
([EnterramentOrgaz] of Obra (Nom "L'enterrament del comte Orgaz") (Any 1588) (Dimensions 172800) (Rellevancia 5) (Complexitat 7) (Sala 2) (pintada_per [ElGreco]) (TéEstil [Manierisme]) (TéTemàtica [Mort]) (TéÉpoca [RenaixementEpoca]))
([Orfena] of Obra (Nom "Jove òrfena al cementiri") (Any 1824) (Dimensions 3564) (Rellevancia 4) (Complexitat 7) (Sala 6) (pintada_per [Delacroix]) (TéEstil [Romanticisme]) (TéTemàtica [Retrat]) (TéÉpoca [Moderna]))
)

(definstances Sales
([Sala1] of Sala (identificador 1) (BasadaEnEpoca [EdatMitjana]) (ContéObra [Verge] [ElJudiciFinal] [Madonna] [AbsideSanCliment] [AbsideSantaMaria] [Flagelacio] [Resurreccio] [Lamentacio]) (conectadaA [Sala7] [Sala2))
([Sala2] of Sala (identificador 2) (BasadaEnEpoca [RenaixementEpoca]) (ContéObra [ElJardin] [LaCreacionDeAdan] [SantJordi] [Parnas] [ElCavaller] [Primavera] [CaçaNeu] [AlegoriaAmor] [VergeMaria] [FugaEgipte] [TentacioCrist] [LaUltimaCena] [LaGioconda] [LaTrinidad] [ElNacimientoDeVenus] [AutoretratDaVinci] [ElionorToledo] [Sibila] [Pecats] [Babel] [VergeRoques] [Calumnia] [EscolaAtenes] [Llebre] [EnterramentOrgaz]) (conectadaA [Sala1] [Sala3]))
([Sala3] of Sala (identificador 3) (BasadaEnEpoca [Barroca]) (ContéObra [NoiaPerla] [PostaDeSol] [JoveCaptaire] [RendicioBreda] [VistaCanal] [EnsenyançaMare] [Danae] [InfantaMargarita] [LesMeninas] [VenusDelEspejo] [PasiajePsique] [NoiaPaons] [CopaPlata] [Lletera] [ArtPintura] [Embarcament] [NensMenjant] [RondaNit] [Buffet] [Costurera] [Plaza]) (conectadaA [Sala2] [Sala4]))
([Sala4] of Sala (identificador 4) (BasadaEnEpoca [Neoclassica]) (ContéObra [SaturnDevorant] [JunioArdiente] [TresMaig] [Juramento] [MortSocrates] [MarteVenus] [NaturaFlors] [Columpi] [ElPetoRobat] [Comics] [LaMaja] [Cincinato] [Wamba] [AlegoriaEstiu] [Concurs] [Napoleo] [DosVells] [DuquesaAlba]) (conectadaA [Sala3] [Sala5]))
([Sala5] of Sala (identificador 5) (BasadaEnEpoca [Romantica]) (ContéObra [TempestaNeu] [Waterloo] [PenyaSegats] [ElCaminante] [PlujaVapor] [LlunaDeMel] [AngelMort] [DonaLloro] [Enterrament] [DonaReclinada] [LesBanyistes] ) (conectadaA [Sala4] [Sala6]))
([Sala6] of Sala (identificador 6) (BasadaEnEpoca [Moderna]) (ContéObra [ElGrito] [AmorDolor] [LaNocheEstrellada] [Xiquets] [MusicaTullerias] [TardaDiumenge] [SolNaciente] [MujerConSombrilla] [LaTerraza] [PontLanglois] [NitCafe] [ElenaRoses] [NaturaMort] [Banyistes] [ElCirc] [Girasols] [LaLibertat] [ElAngel] [LaMatança] [Autoretrat] [TorreCavalls] [Guineus] [Tigres] [RamFlors] [Gerra] [Ansietat] [Peto] [TigreTormenta] [Alger] [JardiGiverny] [Amapoles] [Orfena]) (conectadaA [Sala5] [Sala7]))
([Sala7] of Sala (identificador 7) (BasadaEnEpoca [Contemporanea]) (ContéObra [Guernica] [LesDemoiselles] [ElCarnaval] [ElFillHome] [ComposicioVIII] [LaPersistencia] [CristoDeSanJuan] [LlunaVerda] [Golconda] [ElPeto] [Verd] [FlorersVermells] [Pacient] [DonaPlora] [MortVida] [TresMusics] [Composicio] [BoogieWoogie] [Elefants] [Nighthawks] [NoiaCosint] [NaixementMon] [Dança] [Composicio2] [Temptacions] [ComposicioVIII] [Desintegracio] [Masia] [Automat] [DosFridas] [Pitahaies] [AutoretratMico] [Paralitzat] [TresEdats] [VellGuitarrista]) (conectadaA [Sala6] [Sala1]))
)