(definstances Visitants
([A1] of Adult (Nom "Jaume") (Edat 30) (Coneixement 3) (prefereix-pintors [Rembrandt] [DaVinci] [Goya]) (prefereix-estils [Renaixement] [Romanticisme]) (prefereix-epoques [RenaixementEpoca]) (prefereix-tematiques [Mitologia] [Religio] [Historia]))
([A2] of Adult (Nom "Carles") (Edat 42) (Coneixement 4) (prefereix-pintors [Klimt] [Lorrain] [VanGogh]) (prefereix-estils [Simbolisme] [Postimpressionisme]) (prefereix-epoques [Moderna]) (prefereix-tematiques [Paisatge] [Floral] [Musica]))
([A3] of Adult (Nom "Dolors") (Edat 65) (Coneixement 2) (prefereix-pintors [Monet] [Franz] [Cezanne]) (prefereix-estils [Impressionisme] [Neoclassic]) (prefereix-epoques [Neoclassica]) (prefereix-tematiques [Historia] [Mort] [Amor]))
([A4] of Adult (Nom "Joan") (Edat 24) (Coneixement 2) (prefereix-pintors [ElGreco] [Velazquez] [Goya]) (prefereix-estils [Manierisme] [Rococo] [Romanticisme]) (prefereix-epoques [Romantica]) (prefereix-tematiques [Pobresa] [Erotisme]))
([A5] of Adult (Nom "Xavier") (Edat 38) (Coneixement 4) (prefereix-pintors [MiguelAngel] [Durero]) (prefereix-estils [Manierisme] [Rococo] [Romanticisme]) (prefereix-epoques nil) (prefereix-tematiques [Moral] [Religio]))
([A6] of Adult (Nom "Marta") (Edat 33) (Coneixement 3) (prefereix-pintors [Picasso] [Miro] [Frida] [Magritte]) (prefereix-estils [Cubisme] [Surrealisme] [Naif]) (prefereix-epoques [Contemporanea]) (prefereix-tematiques [Abstracte] [Retrat] [Terror]))
([A7] of Adult (Nom "Ainhoa") (Edat 22) (Coneixement 1) (prefereix-pintors [VanGogh] [Monet]) (prefereix-estils [Impressionisme] [Puntillisme]) (prefereix-epoques [Moderna]) (prefereix-tematiques [Paisatge] [Natura]))
([A8] of Adult (Nom "Pol") (Edat 26) (Coneixement 3) (prefereix-pintors [Rafael] [Turner] [Murillo]) (prefereix-estils [Renaixement] [Barroc]) (prefereix-epoques [Barroca]) (prefereix-tematiques [Espectacle] [NaturaMorta] [Societat]))
([A9] of Adult (Nom "Manel") (Edat 55) (Coneixement 5) (prefereix-pintors [Bronzino] [Vermeer] [Morelli] [Fragonard]) (prefereix-estils [Simbolisme]) (prefereix-epoques [Contemporanea]) (prefereix-tematiques [VidaQuotidiana]))
([A10] of Adult (Nom "Carlota") (Edat 41) (Coneixement 4) (prefereix-pintors [Velazquez] [Rembrandt] [Mondrian]) (prefereix-estils [Realisme] [Neoclassic]) (prefereix-epoques [Neoclassica]) (prefereix-tematiques [Pobresa] [Guerra]))
([A11] of Adult (Nom "Irene") (Edat 37) (Coneixement 3) (prefereix-pintors [Monet] [Sorolla] [MiguelAngel]) (prefereix-estils [Impressionisme] [Flamenc]) (prefereix-epoques [Moderna]) (prefereix-tematiques [Floral] [Amor]))
([A12] of Adult (Nom "Àlex") (Edat 28) (Coneixement 2) (prefereix-pintors [Delacroix] [Picasso]) (prefereix-estils [Expressionisme] [Rococo]) (prefereix-epoques [Romantica]) (prefereix-tematiques [Terror] [VidaQuotidiana]))
([A13] of Adult (Nom "Daniel") (Edat 45) (Coneixement 3) (prefereix-pintors [DaVinci] [Botticelli] [ElBosco]) (prefereix-estils [Renaixemnt] [EscolaFlorentina]) (prefereix-epoques [RenaixementEpoca]) (prefereix-tematiques [Religio] [Mitologia]))
([A14] of Adult (Nom "Raquel") (Edat 26) (Coneixement 1) (prefereix-pintors [MiguelAngel] [Frida]) (prefereix-estils [Barroc]) (prefereix-epoques [Barroca]) (prefereix-tematiques [Mort] [Guerra] [Retrat]))
([A15] of Adult (Nom "Gerard") (Edat 33) (Coneixement 2) (prefereix-pintors [Miro] [Dali] [Picasso]) (prefereix-estils [Surrealisme]) (prefereix-epoques nil) (prefereix-tematiques [Temps] [Espectacle]))
([A16] of Adult (Nom "Nicolas") (Edat 57) (Coneixement 5) (prefereix-pintors [Bruegel] [Giotto] [Friedrich]) (prefereix-estils [Gotic] [Romanticisme]) (prefereix-epoques [EdatMitjana]) (prefereix-tematiques [Religio]))
([A17] of Adult (Nom "Mireia") (Edat 21) (Coneixement 3) (prefereix-pintors [Munch] [Kandinsky] [Magritte]) (prefereix-estils [NeoPlasticisme] [EstilAbstracte]) (prefereix-epoques [Contemporanea]) (prefereix-tematiques [Retrat] [Abstracte]))
([A18] of Adult (Nom "Carmen") (Edat 70) (Coneixement 4) (prefereix-pintors [Leighton] [Goya] [Bruegel]) (prefereix-estils [Neoclassic] [Rococo]) (prefereix-epoques nil) (prefereix-tematiques [Moral] [Amor] [Mort]))
([A19] of Adult (Nom "Josep") (Edat 52) (Coneixement 4) (prefereix-pintors [Sorolla] [VanGogh] [MiguelAngel]) (prefereix-estils [Postimpressionisme] [Renaixement]) (prefereix-epoques [Moderna]) (prefereix-tematiques [NaturaMorta] [Pobresa]))
([A20] of Adult (Nom "Laura") (Edat 31) (Coneixement 2) (prefereix-pintors [Velazquez] [Dali]) (prefereix-estils [Surrealisme]) (prefereix-epoques [Contemporanea]) (prefereix-tematiques [Abstracte] [Temps]))
)

(definstances Nens
([N1] of Nen (Nom "Nil") (Edat 8) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N2] of Nen (Nom "Maria") (Edat 9) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N3] of Nen (Nom "Berta") (Edat 7) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N4] of Nen (Nom "Marc") (Edat 11) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N5] of Nen (Nom "Jan") (Edat 10) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N6] of Nen (Nom "Andrés") (Edat 11) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N7] of Nen (Nom "Leo") (Edat 6) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N8] of Nen (Nom "Eric") (Edat 5) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N9] of Nen (Nom "Eva") (Edat 12) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N10] of Nen (Nom "Jana") (Edat 8) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N11] of Nen (Nom "Samuel") (Edat 7) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N12] of Nen (Nom "Iván") (Edat 11) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N13] of Nen (Nom "Mar") (Edat 12) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N14] of Nen (Nom "Sara") (Edat 13) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N15] of Nen (Nom "Raúl") (Edat 8) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N16] of Nen (Nom "Helena") (Edat 9) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N17] of Nen (Nom "Héctor") (Edat 10) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N18] of Nen (Nom "Alba") (Edat 10) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N19] of Nen (Nom "Ana") (Edat 12) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N20] of Nen (Nom "Alejandro") (Edat 5) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N21] of Nen (Nom "Lucía") (Edat 6) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N22] of Nen (Nom "Martí") (Edat 8) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N23] of Nen (Nom "Esther") (Edat 9) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N24] of Nen (Nom "Albert") (Edat 11) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N25] of Nen (Nom "Aaron") (Edat 13) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N26] of Nen (Nom "Blanca") (Edat 12) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N27] of Nen (Nom "Aitana") (Edat 10) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N28] of Nen (Nom "Chloe") (Edat 7) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N29] of Nen (Nom "Iker") (Edat 8) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
([N30] of Nen (Nom "Pau") (Edat 6) (Coneixement nil) (prefereix-pintors nil) (prefereix-estils nil) (prefereix-epoques nil) (prefereix-tematiques nil))
)

(definstances Adolescents
([AD1] of Adolescent (Nom "Marcos") (Edat 14) (Coneixement 3) (prefereix-pintors [Munch] [Turner] [Vermeer]) (prefereix-estils [Cubisme] [Rococo]) (prefereix-epoques [EdatMitjana]) (prefereix-tematiques [Guerra] [Terror] [Moral]))
([AD2] of Adolescent (Nom "Laia") (Edat 17) (Coneixement 4) (prefereix-pintors [Duccio] [Canaletto] [Courbet]) (prefereix-estils [Romanticisme] [Barroc] [Realisme]) (prefereix-epoques [RenaixementEpoca]) (prefereix-tematiques [Religio] [Mitologia]))
([AD3] of Adolescent (Nom "Georgina") (Edat 17) (Coneixement 3) (prefereix-pintors [Lorrain] [Klimt] [Cabanel]) (prefereix-estils [Flamenc] [Postimpressionisme]) (prefereix-epoques [Neoclassica]) (prefereix-tematiques [Retrat] [Paisatge] [Musica]))
([AD4] of Adolescent (Nom "Irene") (Edat 15) (Coneixement 2) (prefereix-pintors [Seurat] [DaVinci] [MestreTahull]) (prefereix-estils [Impressionisme] [Expressionisme]) (prefereix-epoques [Neoclassica]) (prefereix-tematiques [Espectacle] [VidaQuotidiana]))
([AD5] of Adolescent (Nom "Marc") (Edat 16) (Coneixement 1) (prefereix-pintors [Chardin] [Goya] [ElBosco]) (prefereix-estils [Renaixement] [Gotic]) (prefereix-epoques [EdatMitjana] [Contemporanea]) (prefereix-tematiques [NaturaMorta] [Floral]))
([AD6] of Adolescent (Nom "Pol") (Edat 16) (Coneixement 5) (prefereix-pintors [Velazquez] [Monet] [Sorolla]) (prefereix-estils [Romanic] [Simbolisme]) (prefereix-epoques [Neoclassica]) (prefereix-tematiques [Natura] [Animals] [Temps]))
([AD7] of Adolescent (Nom "Judith") (Edat 17) (Coneixement 4) (prefereix-pintors [Manet] [Cezanne] [Hopper]) (prefereix-estils [Neoclassic] [Manierisme]) (prefereix-epoques [RenaixementEpoca]) (prefereix-tematiques [Mort] [Amor] [Erotisme]))
([AD8] of Adolescent (Nom "Carla") (Edat 15) (Coneixement 3) (prefereix-pintors [Matisse] [Jacques] [Fragonard]) (prefereix-estils [Puntillisme] [Surrealisme]) (prefereix-epoques [Romantica]) (prefereix-tematiques [Societat] [Pobresa]))
([AD9] of Adolescent (Nom "Bernat") (Edat 14) (Coneixement 3) (prefereix-pintors [Bruegel] [Rembrandt] [Frida]) (prefereix-estils [Naif] [EstilAbstracte]) (prefereix-epoques [Moderna]) (prefereix-tematiques [Retrat] [Mort] [Abstracte]))
([AD10] of Adolescent (Nom "Andreu") (Edat 14) (Coneixement 2) (prefereix-pintors [VanGogh] [Murillo] [Miro]) (prefereix-estils [Rococo] [Academicisme]) (prefereix-epoques [Romantica]) (prefereix-tematiques [Terror] [Paisatge]))
([AD11] of Adolescent (Nom "Andrea") (Edat 16) (Coneixement 2) (prefereix-pintors [Monet] [Magritte] [Botticelli]) (prefereix-estils [Classicisme] [Barroc]) (prefereix-epoques [Barroca] [Contemporanea]) (prefereix-tematiques [Religio] [Retrat] [Musica]))
([AD12] of Adolescent (Nom "Leonardo") (Edat 15) (Coneixement 2) (prefereix-pintors [Rafael] [Durero]) (prefereix-estils [Impressionisme] [NeoPlasticisme]) (prefereix-epoques nil) (prefereix-tematiques [Animals]))
([AD13] of Adolescent (Nom "Mireia") (Edat 14) (Coneixement 3) (prefereix-pintors [Franz] [Ribera] [Rousseau]) (prefereix-estils [Renaixement] [Fauvisme]) (prefereix-epoques [Barroca]) (prefereix-tematiques [Societat] [VidaQuotidiana]))
([AD14] of Adolescent (Nom "Martina") (Edat 16) (Coneixement 3) (prefereix-pintors [Delacroix] [Dali] [Mondrian]) (prefereix-estils [Realisme] [Neoclassic]) (prefereix-epoques [RenaixementEpoca]) (prefereix-tematiques [Historia] [Mitologia]))
([AD15] of Adolescent (Nom "Lluis") (Edat 17) (Coneixement 4) (prefereix-pintors [Cimabue] [Goya] [ElGreco]) (prefereix-estils [Romantic]) (prefereix-epoques [Romantica]) (prefereix-tematiques [Amor] [Erotisme]))
([AD16] of Adolescent (Nom "Neus") (Edat 15) (Coneixement 5) (prefereix-pintors [ElBosco] [Turner] [MiguelAngel]) (prefereix-estils [Cubisme] [Expressionisme]) (prefereix-epoques [Moderna]) (prefereix-tematiques [Guerra]))
([AD17] of Adolescent (Nom "Oriol") (Edat 14) (Coneixement 1) (prefereix-pintors [Canaletto] [Picasso] [DaVinci]) (prefereix-estils [EscolaFlorentina] [Naif]) (prefereix-epoques [Contemporanea]) (prefereix-tematiques [Abstracte] [NaturaMorta] [Moral]))
([AD18] of Adolescent (Nom "Guillem") (Edat 15) (Coneixement 2) (prefereix-pintors [Kandinsky] [Leighton] [Velazquez]) (prefereix-estils [Simbolisme] [Postimpressionisme]) (prefereix-epoques [Contemporanea]) (prefereix-tematiques [Natura]))
([AD19] of Adolescent (Nom "Nora") (Edat 17) (Coneixement 2) (prefereix-pintors [Fragonard] [Matisse] [Ribera]) (prefereix-estils [Academicisme] [Renaixement]) (prefereix-epoques [EdatMitjana]) (prefereix-tematiques [Animals] [Religio]))
([AD20] of Adolescent (Nom "Dana") (Edat 15) (Coneixement 3) (prefereix-pintors [Rembrandt] [Friedrich] [VanGogh]) (prefereix-estils [Surrealisme] [EstilAbstracte] [Manierisme]) (prefereix-epoques nil) (prefereix-tematiques [Paisatge]))
([AD21] of Adolescent (Nom "Esteve") (Edat 16) (Coneixement 3) (prefereix-pintors [Bronzino] [Dali] [Miro]) (prefereix-estils [Impressionisme] [Flamenc]) (prefereix-epoques [RenaixementEpoca]) (prefereix-tematiques [Mort] [Terror]))
([AD22] of Adolescent (Nom "Mònica") (Edat 17) (Coneixement 4) (prefereix-pintors [Sorolla] [Klimt] [Munch]) (prefereix-estils [Gotic]) (prefereix-epoques [Neoclassica]) (prefereix-tematiques [Retrat] [Guerra]))
([AD23] of Adolescent (Nom "Sabrina") (Edat 14) (Coneixement 3) (prefereix-pintors [Cimabue] [Seurat] [Manet]) (prefereix-estils [NeoPlasticisme] [Rococo]) (prefereix-epoques [Moderna]) (prefereix-tematiques [Religio] [Moral]))
([AD24] of Adolescent (Nom "Carlos") (Edat 14) (Coneixement 2) (prefereix-pintors [Botticelli] [MiguelAngel] [Picasso]) (prefereix-estils [Barroc] [Neoclassic]) (prefereix-epoques [Contemporanea]) (prefereix-tematiques [VidaQuotidiana] [Paisatge]))
([AD25] of Adolescent (Nom "Amèlia") (Edat 15) (Coneixement 3) (prefereix-pintors [Monet] [Courbet] [Franz]) (prefereix-estils [Expressionisme] [Fauvisme]) (prefereix-epoques [Barroca]) (prefereix-tematiques [NaturaMorta]))
([AD26] of Adolescent (Nom "Diego") (Edat 17) (Coneixement 2) (prefereix-pintors [Frida] [DaVinci] [Vermeer]) (prefereix-estils [Cubisme] [Surrealisme]) (prefereix-epoques [Barroca]) (prefereix-tematiques [Espectacle] [Musica]))
([AD27] of Adolescent (Nom "Eda") (Edat 16) (Coneixement 1) (prefereix-pintors [Jacques] [Giotto] [ElGreco]) (prefereix-estils [Impressionisme] [Postimpressionisme]) (prefereix-epoques [Moderna]) (prefereix-tematiques [Pobresa] [Abstracte]))
([AD28] of Adolescent (Nom "Duna") (Edat 15) (Coneixement 4) (prefereix-pintors [Morelli] [Hopper] [Friedrich]) (prefereix-estils [Naif]) (prefereix-epoques [Romantica]) (prefereix-tematiques [Historia] [Erotisme]))
([AD29] of Adolescent (Nom "David") (Edat 17) (Coneixement 4) (prefereix-pintors [Mondrian] [Delacroix] [Cezanne]) (prefereix-estils [EscolaFlorentina] [Flamenc]) (prefereix-epoques [Romantica]) (prefereix-tematiques [Floral] [Natura]))
([AD30] of Adolescent (Nom "Rafa") (Edat 14) (Coneixement 3) (prefereix-pintors [Rafael] [Bruegel] [Goya]) (prefereix-estils [Classicisme] [Romanticisme]) (prefereix-epoques [Moderna]) (prefereix-tematiques [Historia]))
)

(definstances Visites
([Visita-Actual] of Visita (Dies 3) (Duracio 2) (formada_per [A1] [A2] [A3] [A4] [A5] [A6] [A7] [A8] [A9] [A10] [A11] [A12] [A13] [A14] [A15] [A16] [A17] [A18] [A19] [A20] [N1] [N2] [N3] [N4] [N5] [N6] [N7] [N8] [N9] [N10] [N11] [N12] [N13] [N14] [N15] [N16] [N17] [N18] [N19] [N20] [N21] [N22] [N23] [N24] [N25] [N26] [N27] [N28] [N29] [N30] [AD1] [AD2] [AD3] [AD4] [AD5] [AD6] [AD7] [AD8] [AD9] [AD10] [AD11] [AD12] [AD13] [AD14] [AD15] [AD16] [AD17] [AD18] [AD19] [AD20] [AD20] [AD21] [AD22] [AD23] [AD24] [AD25] [AD26] [AD27] [AD28] [AD29] [AD30]) (VisitaObra nil))
)